sudo: false
language: java
jdk: openjdk12

after_success:
  - cp target/tv-*.war docker/arm32/
  - cp target/tv-*.war docker/x86-64/
  - docker build -t sulrich423/tv:arm32 docker/arm32
  - docker build -t sulrich423/tv:x86-64 docker/x86-64
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sulrich423/tv:arm32
  - docker push sulrich423/tv:x86-64
