version: '3'
services:
  mysql:
    container_name: mysql
    image: "mysql/mysql-server:8.0.29"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tv
      MYSQL_PASSWORD: tv
      MYSQL_DATABASE: tv
  tv:
    container_name: tv
    image: "sulrich423/tv:latest"
    ports:
      - "8080:8080"
    depends_on: 
     - mysql
