version: '3'
services:
  mysql:
    container_name: mysql
    image: "mysql:8.0.16"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tv
      MYSQL_ROOT_HOST: 127.0.0.1
  tv:
    container_name: tv
    image: "sulrich423/tv:latest"
    ports:
      - "8080:8080"
