name: Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package
    - name: copy war to docker
      run: cp target/tv-*.war docker/arm32/ && cp target/tv-*.war docker/x86-64/
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image and push arm
      uses: docker/build-push-action@v2
      with:
        context: ./docker/arm32
        tags: sulrich423/tv:arm32
        push: ${{ github.event_name != 'pull_request' }}
    - name: Build image and push x86-64
      uses: docker/build-push-action@v2
      with:
        context: ./docker/x86-64
        tags: sulrich423/tv:x86-64
        push: ${{ github.event_name != 'pull_request' }}
